name: Notify Slack on Push to Main

# Trigger this workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Check if SLACK_BOT_TOKEN is set
    - name: Verify SLACK_BOT_TOKEN secret
      run: |
        if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
          echo "SLACK_BOT_TOKEN is empty or not set"
        else
          echo "SLACK_BOT_TOKEN is set correctly"
        fi

    # Step 3: Send message to Slack using curl and the Slack API
    - name: Send Slack notification
      run: |
        curl -X POST https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data '{
            "channel": "C07EC64UVDY",   # Replace with your channel ID or channel name
            "text": "Code has been pushed to the main branch!"
          }'
