name: Send Notification to Slack

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Send message to Slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: C07EC64UVDY
        slack-message: "A new push to main branch"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
