name: Deploy to Netlify and notify Slack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=build --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --message "Automated deployment from GitHub Actions"
        continue-on-error: true  # Continue the workflow even if this step fails

  slack-notification:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Send Slack Notification
        if: always()  # Runs regardless of job success or failure
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "channel": "C07EC64UVDY",
              "text": "Deployment to Netlify has completed with status: ${{ job.status }}."
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
