name: Deploy to Netlify and notify Slack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Netlify
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir=build --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
        
  slack-notification:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Send Slack Notification
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-message: "Deployment to Netlify was successful.Happy vibes!!!."
          channel-id: 'C07EC64UVDY'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
