name: Deploy to Netlify and notify Slack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@v1
        with:
          args: deploy --prod --dir=build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  slack-notification:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Send Slack Notification
        if: always()  # Runs regardless of job success or failure
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload: |
            {
              "channel": "C07EC64UVDY",
              "text": "Deployment to Netlify has completed with status: ${{ job.status }}."
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
